// Code generated by protoc-gen-go. DO NOT EDIT.
// source: patch.proto

/*
Package patch is a generated protocol buffer package.

It is generated from these files:
	patch.proto

It has these top-level messages:
	ProtoPatch
	ProtoOp
	ProtoStep
*/
package patch

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProtoAction int32

const (
	ProtoAction_ActionInvalid    ProtoAction = 0
	ProtoAction_ActionReplace    ProtoAction = 1
	ProtoAction_ActionAppend     ProtoAction = 2
	ProtoAction_ActionRemove     ProtoAction = 3
	ProtoAction_ActionRemoveOne  ProtoAction = 4
	ProtoAction_ActionReplaceOne ProtoAction = 5
	ProtoAction_ActionAppendOne  ProtoAction = 6
	ProtoAction_ActionStrPatch   ProtoAction = 7
	ProtoAction_ActionStepInto   ProtoAction = 8
)

var ProtoAction_name = map[int32]string{
	0: "ActionInvalid",
	1: "ActionReplace",
	2: "ActionAppend",
	3: "ActionRemove",
	4: "ActionRemoveOne",
	5: "ActionReplaceOne",
	6: "ActionAppendOne",
	7: "ActionStrPatch",
	8: "ActionStepInto",
}
var ProtoAction_value = map[string]int32{
	"ActionInvalid":    0,
	"ActionReplace":    1,
	"ActionAppend":     2,
	"ActionRemove":     3,
	"ActionRemoveOne":  4,
	"ActionReplaceOne": 5,
	"ActionAppendOne":  6,
	"ActionStrPatch":   7,
	"ActionStepInto":   8,
}

func (x ProtoAction) String() string {
	return proto.EnumName(ProtoAction_name, int32(x))
}
func (ProtoAction) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ProtoPatch struct {
	NewValues *google_protobuf.Any `protobuf:"bytes,1,opt,name=newValues" json:"newValues,omitempty"`
	Ops       []*ProtoOp           `protobuf:"bytes,2,rep,name=ops" json:"ops,omitempty"`
}

func (m *ProtoPatch) Reset()                    { *m = ProtoPatch{} }
func (m *ProtoPatch) String() string            { return proto.CompactTextString(m) }
func (*ProtoPatch) ProtoMessage()               {}
func (*ProtoPatch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ProtoPatch) GetNewValues() *google_protobuf.Any {
	if m != nil {
		return m.NewValues
	}
	return nil
}

func (m *ProtoPatch) GetOps() []*ProtoOp {
	if m != nil {
		return m.Ops
	}
	return nil
}

type ProtoOp struct {
	Path []*ProtoStep `protobuf:"bytes,1,rep,name=Path" json:"Path,omitempty"`
}

func (m *ProtoOp) Reset()                    { *m = ProtoOp{} }
func (m *ProtoOp) String() string            { return proto.CompactTextString(m) }
func (*ProtoOp) ProtoMessage()               {}
func (*ProtoOp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ProtoOp) GetPath() []*ProtoStep {
	if m != nil {
		return m.Path
	}
	return nil
}

type ProtoStep struct {
	Tag        int32       `protobuf:"varint,1,opt,name=Tag" json:"Tag,omitempty"`
	Name       string      `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	JsonName   string      `protobuf:"bytes,3,opt,name=JsonName" json:"JsonName,omitempty"`
	Action     ProtoAction `protobuf:"varint,4,opt,name=Action,enum=patch.ProtoAction" json:"Action,omitempty"`
	SrcIndex   int32       `protobuf:"varint,5,opt,name=SrcIndex" json:"SrcIndex,omitempty"`
	DstIndex   int32       `protobuf:"varint,6,opt,name=DstIndex" json:"DstIndex,omitempty"`
	StrMapKey  string      `protobuf:"bytes,7,opt,name=StrMapKey" json:"StrMapKey,omitempty"`
	IntMapKey  int64       `protobuf:"varint,8,opt,name=IntMapKey" json:"IntMapKey,omitempty"`
	UIntMapKey uint64      `protobuf:"varint,9,opt,name=UIntMapKey" json:"UIntMapKey,omitempty"`
	BoolMapKey bool        `protobuf:"varint,10,opt,name=BoolMapKey" json:"BoolMapKey,omitempty"`
}

func (m *ProtoStep) Reset()                    { *m = ProtoStep{} }
func (m *ProtoStep) String() string            { return proto.CompactTextString(m) }
func (*ProtoStep) ProtoMessage()               {}
func (*ProtoStep) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ProtoStep) GetTag() int32 {
	if m != nil {
		return m.Tag
	}
	return 0
}

func (m *ProtoStep) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProtoStep) GetJsonName() string {
	if m != nil {
		return m.JsonName
	}
	return ""
}

func (m *ProtoStep) GetAction() ProtoAction {
	if m != nil {
		return m.Action
	}
	return ProtoAction_ActionInvalid
}

func (m *ProtoStep) GetSrcIndex() int32 {
	if m != nil {
		return m.SrcIndex
	}
	return 0
}

func (m *ProtoStep) GetDstIndex() int32 {
	if m != nil {
		return m.DstIndex
	}
	return 0
}

func (m *ProtoStep) GetStrMapKey() string {
	if m != nil {
		return m.StrMapKey
	}
	return ""
}

func (m *ProtoStep) GetIntMapKey() int64 {
	if m != nil {
		return m.IntMapKey
	}
	return 0
}

func (m *ProtoStep) GetUIntMapKey() uint64 {
	if m != nil {
		return m.UIntMapKey
	}
	return 0
}

func (m *ProtoStep) GetBoolMapKey() bool {
	if m != nil {
		return m.BoolMapKey
	}
	return false
}

func init() {
	proto.RegisterType((*ProtoPatch)(nil), "patch.ProtoPatch")
	proto.RegisterType((*ProtoOp)(nil), "patch.ProtoOp")
	proto.RegisterType((*ProtoStep)(nil), "patch.ProtoStep")
	proto.RegisterEnum("patch.ProtoAction", ProtoAction_name, ProtoAction_value)
}

func init() { proto.RegisterFile("patch.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 397 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x92, 0xcf, 0x8e, 0xd3, 0x30,
	0x10, 0x87, 0x71, 0x93, 0xfe, 0xc9, 0x14, 0x8a, 0x19, 0xf6, 0x10, 0x56, 0x08, 0x59, 0x15, 0x87,
	0x68, 0x0f, 0xa9, 0x14, 0x9e, 0xa0, 0x88, 0x4b, 0x40, 0xb0, 0x95, 0x03, 0xdc, 0xdd, 0xd4, 0x74,
	0x57, 0xca, 0xda, 0x56, 0xe2, 0x5d, 0xe8, 0x43, 0xf1, 0x0c, 0xbc, 0x1a, 0xb2, 0x9d, 0x6d, 0xb2,
	0xb7, 0x99, 0xef, 0xfb, 0x79, 0xc6, 0x96, 0x0c, 0x4b, 0x23, 0x6c, 0x7d, 0x93, 0x9b, 0x56, 0x5b,
	0x8d, 0x53, 0xdf, 0x5c, 0xbe, 0x39, 0x6a, 0x7d, 0x6c, 0xe4, 0xc6, 0xc3, 0xfd, 0xfd, 0xaf, 0x8d,
	0x50, 0xa7, 0x90, 0x58, 0xef, 0x01, 0x76, 0xae, 0xd8, 0xb9, 0x20, 0x16, 0x90, 0x28, 0xf9, 0xfb,
	0xa7, 0x68, 0xee, 0x65, 0x97, 0x12, 0x46, 0xb2, 0x65, 0x71, 0x91, 0x87, 0xc3, 0xf9, 0xe3, 0xe1,
	0x7c, 0xab, 0x4e, 0x7c, 0x88, 0x21, 0x83, 0x48, 0x9b, 0x2e, 0x9d, 0xb0, 0x28, 0x5b, 0x16, 0xab,
	0x3c, 0xac, 0xf7, 0x33, 0xaf, 0x0d, 0x77, 0x6a, 0xbd, 0x81, 0x79, 0xdf, 0xe3, 0x7b, 0x88, 0x77,
	0xc2, 0xde, 0xa4, 0xc4, 0xa7, 0xe9, 0x38, 0x5d, 0x59, 0x69, 0xb8, 0xb7, 0xeb, 0xbf, 0x13, 0x48,
	0xce, 0x0c, 0x29, 0x44, 0xdf, 0xc5, 0xd1, 0x5f, 0x67, 0xca, 0x5d, 0x89, 0x08, 0xf1, 0x37, 0x71,
	0x27, 0xd3, 0x09, 0x23, 0x59, 0xc2, 0x7d, 0x8d, 0x97, 0xb0, 0xf8, 0xdc, 0x69, 0xe5, 0x79, 0xe4,
	0xf9, 0xb9, 0xc7, 0x2b, 0x98, 0x6d, 0x6b, 0x7b, 0xab, 0x55, 0x1a, 0x33, 0x92, 0xad, 0x0a, 0x1c,
	0xef, 0x0d, 0x86, 0xf7, 0x09, 0x37, 0xa7, 0x6a, 0xeb, 0x52, 0x1d, 0xe4, 0x9f, 0x74, 0xea, 0x57,
	0x9e, 0x7b, 0xe7, 0x3e, 0x75, 0x36, 0xb8, 0x59, 0x70, 0x8f, 0x3d, 0xbe, 0x85, 0xa4, 0xb2, 0xed,
	0x57, 0x61, 0xbe, 0xc8, 0x53, 0x3a, 0xf7, 0x17, 0x18, 0x80, 0xb3, 0xa5, 0xb2, 0xbd, 0x5d, 0x30,
	0x92, 0x45, 0x7c, 0x00, 0xf8, 0x0e, 0xe0, 0xc7, 0xa0, 0x13, 0x46, 0xb2, 0x98, 0x8f, 0x88, 0xf3,
	0x1f, 0xb5, 0x6e, 0x7a, 0x0f, 0x8c, 0x64, 0x0b, 0x3e, 0x22, 0x57, 0xff, 0x08, 0x2c, 0x47, 0x6f,
	0xc1, 0x57, 0xf0, 0x22, 0x54, 0xa5, 0x7a, 0x10, 0xcd, 0xed, 0x81, 0x3e, 0x1b, 0x10, 0x97, 0xa6,
	0x11, 0xb5, 0xa4, 0x04, 0x29, 0x3c, 0x0f, 0x68, 0x6b, 0x8c, 0x54, 0x07, 0x3a, 0x19, 0x08, 0x97,
	0x77, 0xfa, 0x41, 0xd2, 0x08, 0x5f, 0xc3, 0xcb, 0x31, 0xb9, 0x56, 0x92, 0xc6, 0x78, 0x01, 0xf4,
	0xc9, 0x2c, 0x47, 0xa7, 0x43, 0x34, 0x8c, 0x73, 0x70, 0x86, 0x08, 0xab, 0x00, 0x2b, 0xdb, 0xfa,
	0x2f, 0x46, 0xe7, 0x63, 0x26, 0x4d, 0xa9, 0xac, 0xa6, 0x8b, 0xfd, 0xcc, 0xff, 0xae, 0x0f, 0xff,
	0x03, 0x00, 0x00, 0xff, 0xff, 0x31, 0x22, 0x04, 0x58, 0xbe, 0x02, 0x00, 0x00,
}
